# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: constraintViolationList
    serializer:
        serialize_null: true
    view:
        view_response_listener:  true
    exception:
        serializer_error_renderer: true
        codes:
            InvalidArgumentException: 400
        messages:
            InvalidArgumentException: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }