version: '3.7'
services:
  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${HOST_DB_PORT:-5432}:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '${HOST_REDIS_PORT:-6379}:6379'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/opt/app'
    depends_on:
      - database
      - redis
  nginx:
    image: nginx:1.22-alpine
    volumes:
      - './public/:/opt/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${HOST_PORT:-8080}:80'
    depends_on:
      - php
volumes:
  db-data:
